### ISSUE TITLE
NoMethodError raised when server is not an NTP server

### ISSUE THREAD

**Issue by aramprice** [zencoder/net-ntp#8]
When connecting to a non-NTP server `NoMethodError` is raised from [lib/net/ntp/ntp.rb:80](https://github.com/zencoder/net-ntp/blob/master/lib/net/ntp/ntp.rb#L80)

Ex:

``` ruby
Net::NTP.get("www.google.com", "ntp", 3).time 
```

in v2.1.1 `Timeout::Error` was returned.

**Comment by shortdudey123** [comment]
Looks like this happens anytime a timeout value is passed to the get method even though the code that it errors on actually appears to work when run manually
```
[1] pry(main)> require 'net/ntp'
=> true
[2] pry(main)> t = Net::NTP.get('time.nist.gov', 'ntp', 0.1)

From: /Users/grantridder/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/net-ntp-2.1.2/lib/net/ntp/ntp.rb @ line 79 Net::NTP.get:

    66: def self.get(host="pool.ntp.org", port="ntp", timeout=TIMEOUT)
    67:   sock = UDPSocket.new
    68:   sock.connect(host, port)
    69: 
    70:   client_localtime      = Time.now.to_f
    71:   client_adj_localtime  = client_localtime + NTP_ADJ
    72:   client_frac_localtime = frac2bin(client_adj_localtime)
    73: 
    74:   ntp_msg = (['00011011']+Array.new(12, 0)+[client_localtime, client_frac_localtime.to_s]).pack("B8 C3 N10 B32")
    75: 
    76:   sock.print ntp_msg
    77:   sock.flush
    78:   require 'pry'
 => 79:   binding.pry
    80:   read, write, error = IO.select [sock], nil, nil, timeout
    81:   if read[0]
    82:     client_time_receive = Time.now.to_f
    83:     data, _ = sock.recvfrom(960)
    84:     Response.new(data, client_time_receive)
    85:   else
    86:     # For backwards compatibility we throw a Timeout error, even
    87:     # though the timeout is being controlled by select()
    88:     raise Timeout::Error
    89:   end
    90: end

[1] pry(Net::NTP)> read, write, error = IO.select [sock], nil, nil, timeout      
=> [[#<UDPSocket:fd 8>], [], []]
[2] pry(Net::NTP)> if read[0]      
[2] pry(Net::NTP)*   client_time_receive = Time.now.to_f        
[2] pry(Net::NTP)*   data, _ = sock.recvfrom(960)        
[2] pry(Net::NTP)*   Response.new(data, client_time_receive)        
[2] pry(Net::NTP)* else        
[2] pry(Net::NTP)*   # For backwards compatibility we throw a Timeout error, even        
[2] pry(Net::NTP)*   # though the timeout is being controlled by select()        
[2] pry(Net::NTP)*   raise Timeout::Error        
[2] pry(Net::NTP)* end        
=> #<Net::NTP::Response:0x007fe1aa180db0
 @client_time_receive=1421977104.3917031,
 @packet_data_by_field=nil,
 @raw_data="\x1C\x01\x00\xE3\x00\x00\x00\x00\x00\x00\x00\x00ACTS\xD8l$Q\x0E.\xE12T\xC1\xA6\x04\x9F\x0E8p\xD8l$\x84-$\x84\xD1\xD8l$\x84-$\xE4\xE6">
[3] pry(Net::NTP)> exit
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/grantridder/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/net-ntp-2.1.2/lib/net/ntp/ntp.rb:81:in `get'
[3] pry(main)> 
```

**Comment by shortdudey123** [comment]
Changing `if read[0]` to `unless read.nil?` appears to solve the issue.  Will open PR

```
[1] pry(main)> require 'net/ntp'
=> true
[2] pry(main)> t = Net::NTP.get()
=> #<Net::NTP::Response:0x007f90d29e4fe8
 @client_time_receive=1421977832.45788,
 @packet_data_by_field=nil,
 @raw_data="\x1C\x02\x03\xEA\x00\x00\x00A\x00\x00\f]\x82\xCF\xF4\xF0\xD8l\x1Fh\xC7\xA3]\rT\xC1\xA8\xE8\x9E'2P\xD8l'h3\xF70/\xD8l'h3\xFART">
[3] pry(main)> t = Net::NTP.get('time.nist.gov', 'ntp', 0.1)
Timeout::Error: Timeout::Error
from /Users/grantridder/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/net-ntp-2.1.2/lib/net/ntp/ntp.rb:88:in `get'
[4] pry(main)> t = Net::NTP.get('www.google.com')
Timeout::Error: Timeout::Error
from /Users/grantridder/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/net-ntp-2.1.2/lib/net/ntp/ntp.rb:88:in `get'
[5] pry(main)> 
```

**Comment by shortdudey123** [comment]
Solution: https://github.com/zencoder/net-ntp/pull/9

**Comment by aramprice** [comment]
Great news, thanks!

**Comment by shortdudey123** [comment]
My fork has the bug fixed on the master branch (https://github.com/shortdudey123/net-ntp)
`gem 'net-ntp', github: 'shortdudey123/net-ntp'`

**Comment by nate** [comment]
Version 2.1.3 is pushed with this change.
